package com.athar.ingestion.notificationlistener

/**
 * Default package allow-list for the Play-Store-safe notification ingestion path.
 *
 * Exact package names are used where they are well-known. Brand-keyword matching covers package
 * suffix variants across Saudi banks and common global finance apps without exposing notification
 * ingestion to arbitrary apps.
 */
object BankNotificationPackageMatcher : BankPackageFilter {
    private val exactPackages = setOf(
        "com.alrajhibank.AlRajhiMobile",
        "com.alrajhibank.alrajhimobile",
        "com.google.android.apps.walletnfcrel",
        "com.google.android.apps.nbu.paisa.user",
        "com.samsung.android.spay",
        "com.samsung.android.spayfw",
        "com.paypal.android.p2pmobile",
        "com.venmo",
        "com.squareup.cash",
        "com.americanexpress.android.acctsvcs.us",
        "com.infonow.bofa",
        "com.wf.wellsfargomobile",
        "com.citi.citimobile",
        "com.usaa.mobile.android.usaa",
        "uk.co.hsbc.hsbcukmobilebanking",
        "com.barclays.android.barclaysmobilebanking",
        "com.lloydsbank.mobilebank",
        "com.natwest.mobile",
        "uk.co.santander.santanderUK",
        "com.usbank.mobilebanking",
        "com.pnc.ecommerce.mobile",
        "com.sofi.mobile",
        "com.transferwise.android",
        "com.payoneer.android",
        "com.remitly.androidapp",
    )

    private val packageKeywords = listOf(
        "alrajhi",
        "stcpay",
        "stcbank",
        "d360",
        "barq",
        "alinma",
        "riyad",
        "snb",
        "alahli",
        "anb",
        "albilad",
        "bsf",
        "saib",
        "jazira",
        "emiratesnbd",
        "adcb",
        "mashreq",
        "bankfab",
        "qnb",
        "boubyan",
        "kfh",
        "bankmuscat",
        "wise",
        "transferwise",
        "revolut",
        "chase",
        "capitalone",
        "mercury",
        "monzo",
        "n26",
        "starling",
        "hsbc",
        "barclays",
        "lloyds",
        "natwest",
        "santander",
        "halifax",
        "usbank",
        "pnc",
        "sofi",
        "paisa",
        "samsung.android.spay",
        "paypal",
        "venmo",
        "americanexpress",
        "amex",
        "bankofamerica",
        "bofa",
        "wellsfargo",
        "citimobile",
        "usaa",
        "discoverfinancial",
        "truist",
        "citizensbank",
        "payoneer",
        "remitly",
        "westernunion",
        "bunq",
        "nubank",
        "bbva",
        "scotiabank",
        "tdbank",
        "rbc",
        "commbank",
        "westpac",
        "nab.mobile",
        "anz.android",
        "dbsmbanking",
        "ocbc",
        "uob",
        "maybank",
        "cimb",
        "hdfcbank",
        "icici",
        "axisbank",
        "kotak",
    )

    override fun isBankPackage(packageName: String): Boolean {
        val trimmed = packageName.trim()
        if (trimmed in exactPackages) return true
        val lower = trimmed.lowercase()
        return packageKeywords.any { lower.contains(it) }
    }
}
